#ifndef LONG_REST_GLOBAL_HEADER
#define LONG_REST_GLOBAL_HEADER

#define LONG_REST_VERSION "LongREST v1.0.5"
#define LONG_REST_VERSION_MAJOR 1
#define LONG_REST_VERSION_MINOR 0
#define LONG_REST_VERSION_PATCH 5

#endif